export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  OPS_MANAGER = 'OPS_MANAGER',
  OPS_EXECUTIVE = 'OPS_EXECUTIVE',
  SALES = 'SALES',
  FINANCE = 'FINANCE',
  COMPLIANCE = 'COMPLIANCE',
  OPS = 'OPS', 
}
